# frozen_string_literal: true

# Seed data for exercises table
# Run with: rails db:seed:exercises

EXERCISES_DATA = [
  # ============================================================
  # CHEST (가슴)
  # ============================================================
  {
    name: "푸시업",
    english_name: "push_up",
    display_name: "푸시업",
    muscle_group: "chest",
    secondary_muscles: %w[triceps shoulders core],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium short],
    description: "가장 기본적인 상체 밀기 운동",
    form_tips: "팔꿈치 45도 유지, 몸 전체 일직선, 가슴이 바닥에 가깝게",
    common_mistakes: "허리가 처지거나 엉덩이가 들림, 팔꿈치가 너무 벌어짐"
  },
  {
    name: "샤크 푸시업",
    english_name: "shark_push_up",
    display_name: "샤크 푸시업",
    muscle_group: "chest",
    secondary_muscles: %w[triceps shoulders],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[shark_rack],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium short],
    description: "샤크랙을 이용한 푸시업, 난이도 조절 가능",
    form_tips: "칸 수로 난이도 조절, 낮은 칸일수록 어려움",
    common_mistakes: "너무 쉬운 칸으로 시작, 가동범위 부족"
  },
  {
    name: "벤치프레스",
    english_name: "bench_press",
    display_name: "벤치프레스",
    muscle_group: "chest",
    secondary_muscles: %w[triceps shoulders],
    movement_pattern: "push",
    fitness_factors: %w[strength power],
    equipment: %w[barbell bench],
    difficulty: 3,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "가슴 근력 발달의 핵심 운동",
    form_tips: "견갑골 모으기, 발은 바닥에 고정, 바벨 경로는 직선",
    common_mistakes: "어깨가 들림, 팔꿈치 각도 불안정, 바운스 사용"
  },
  {
    name: "인클라인 벤치프레스",
    english_name: "incline_bench_press",
    display_name: "인클라인 벤치프레스",
    muscle_group: "chest",
    secondary_muscles: %w[triceps shoulders],
    movement_pattern: "push",
    fitness_factors: %w[strength],
    equipment: %w[barbell incline_bench],
    difficulty: 3,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "상부 가슴 발달에 효과적",
    form_tips: "벤치 각도 30-45도, 상부 가슴에 집중",
    common_mistakes: "각도가 너무 높으면 어깨 운동이 됨"
  },
  {
    name: "덤벨 프레스",
    english_name: "dumbbell_press",
    display_name: "덤벨 프레스",
    muscle_group: "chest",
    secondary_muscles: %w[triceps shoulders],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[dumbbell bench],
    difficulty: 2,
    min_level: 2,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "덤벨을 이용한 가슴 프레스",
    form_tips: "가동범위를 최대로, 가슴 스트레칭 느끼기",
    common_mistakes: "덤벨이 너무 넓게 벌어짐"
  },
  {
    name: "딥스",
    english_name: "dips",
    display_name: "딥스",
    muscle_group: "chest",
    secondary_muscles: %w[triceps shoulders],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[dip_station],
    difficulty: 3,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "상체를 앞으로 기울이면 가슴, 세우면 삼두",
    form_tips: "가슴 타겟 시 상체 앞으로 기울이기",
    common_mistakes: "어깨가 말려들어감, 가동범위 부족"
  },

  # ============================================================
  # BACK (등)
  # ============================================================
  {
    name: "턱걸이",
    english_name: "pull_up",
    display_name: "턱걸이",
    muscle_group: "back",
    secondary_muscles: %w[biceps forearms core],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[pull_up_bar],
    difficulty: 4,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "등 근육 발달의 왕도",
    form_tips: "견갑골 먼저 내리고 당기기, 팔꿈치를 뒤로",
    common_mistakes: "팔로만 당김, 반동 사용, 가동범위 부족"
  },
  {
    name: "샤크 턱걸이",
    english_name: "shark_pull_up",
    display_name: "샤크 턱걸이",
    muscle_group: "back",
    secondary_muscles: %w[biceps forearms],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[shark_rack],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium short],
    description: "샤크랙을 이용한 보조 턱걸이",
    form_tips: "칸 수로 난이도 조절, 등 수축에 집중",
    common_mistakes: "팔로만 당김"
  },
  {
    name: "렛풀다운",
    english_name: "lat_pulldown",
    display_name: "렛풀다운",
    muscle_group: "back",
    secondary_muscles: %w[biceps],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[cable machine],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium short],
    description: "광배근 타겟 케이블 운동",
    form_tips: "가슴을 펴고 바를 쇄골 쪽으로 당기기",
    common_mistakes: "상체가 너무 뒤로 젖혀짐, 팔로만 당김"
  },
  {
    name: "데드리프트",
    english_name: "deadlift",
    display_name: "데드리프트",
    muscle_group: "back",
    secondary_muscles: %w[legs glutes hamstrings core],
    movement_pattern: "hinge",
    fitness_factors: %w[strength power],
    equipment: %w[barbell],
    difficulty: 4,
    min_level: 2,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: false,
    rom_options: %w[full],
    description: "전신 근력의 기본, 후면 사슬 발달",
    form_tips: "허리 곧게, 바벨 몸에 붙여서, 코어 힘주기",
    common_mistakes: "허리가 둥글게 말림, 바벨이 몸에서 떨어짐"
  },
  {
    name: "바벨로우",
    english_name: "barbell_row",
    display_name: "바벨로우",
    muscle_group: "back",
    secondary_muscles: %w[biceps rear_delts],
    movement_pattern: "pull",
    fitness_factors: %w[strength],
    equipment: %w[barbell],
    difficulty: 3,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "등 두께 발달에 효과적",
    form_tips: "상체 45도 유지, 팔꿈치를 뒤로 당기기",
    common_mistakes: "상체가 너무 일어남, 반동 사용"
  },
  {
    name: "시티드로우",
    english_name: "seated_row",
    display_name: "시티드로우",
    muscle_group: "back",
    secondary_muscles: %w[biceps rear_delts],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[cable machine],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "등 중앙부 발달에 효과적",
    form_tips: "가슴 펴고, 견갑골 모으며 당기기",
    common_mistakes: "상체 스윙, 어깨가 앞으로 말림"
  },

  # ============================================================
  # LEGS (하체)
  # ============================================================
  {
    name: "기둥 스쿼트",
    english_name: "pole_squat",
    display_name: "기둥 스쿼트",
    muscle_group: "legs",
    secondary_muscles: %w[glutes core],
    movement_pattern: "squat",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[pole],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium short],
    description: "기둥을 잡고 하는 보조 스쿼트",
    form_tips: "무릎이 발끝 방향, 허벅지 평행까지 내려가기",
    common_mistakes: "무릎이 안쪽으로 모임, 가동범위 부족"
  },
  {
    name: "맨몸 스쿼트",
    english_name: "bodyweight_squat",
    display_name: "맨몸 스쿼트",
    muscle_group: "legs",
    secondary_muscles: %w[glutes core],
    movement_pattern: "squat",
    fitness_factors: %w[strength muscular_endurance cardiovascular],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium short],
    description: "기본 하체 운동",
    form_tips: "발 어깨너비, 발끝 약간 바깥, 가슴 펴기",
    common_mistakes: "무릎이 안쪽으로, 허리가 둥글게"
  },
  {
    name: "바벨 스쿼트",
    english_name: "barbell_squat",
    display_name: "바벨 스쿼트",
    muscle_group: "legs",
    secondary_muscles: %w[glutes core back],
    movement_pattern: "squat",
    fitness_factors: %w[strength power],
    equipment: %w[barbell squat_rack],
    difficulty: 4,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: false,
    rom_options: %w[full medium],
    description: "하체 근력의 핵심 운동",
    form_tips: "바벨 위치(하이바/로우바), 코어 힘주기",
    common_mistakes: "무릎 cave-in, 앞으로 쏠림, 허리 라운딩"
  },
  {
    name: "런지",
    english_name: "lunge",
    display_name: "런지",
    muscle_group: "legs",
    secondary_muscles: %w[glutes core],
    movement_pattern: "squat",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[none],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "한 발씩 번갈아 하는 하체 운동",
    form_tips: "앞 무릎 90도, 뒷 무릎이 바닥 가깝게",
    common_mistakes: "무릎이 발끝을 넘음, 상체가 앞으로 숙여짐"
  },
  {
    name: "레그프레스",
    english_name: "leg_press",
    display_name: "레그프레스",
    muscle_group: "legs",
    secondary_muscles: %w[glutes],
    movement_pattern: "squat",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[machine],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "머신을 이용한 하체 프레스",
    form_tips: "발 위치로 타겟 근육 조절 가능",
    common_mistakes: "무릎 락아웃, 엉덩이가 들림"
  },
  {
    name: "레그컬",
    english_name: "leg_curl",
    display_name: "레그컬",
    muscle_group: "legs",
    secondary_muscles: %w[hamstrings],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[machine],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "햄스트링 고립 운동",
    form_tips: "천천히 수축, 최대 수축 지점에서 잠시 유지",
    common_mistakes: "반동 사용, 가동범위 부족"
  },
  {
    name: "레그익스텐션",
    english_name: "leg_extension",
    display_name: "레그익스텐션",
    muscle_group: "legs",
    secondary_muscles: %w[quadriceps],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[machine],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "대퇴사두근 고립 운동",
    form_tips: "무릎 완전 펴기, 정점에서 수축",
    common_mistakes: "반동 사용, 엉덩이가 들림"
  },
  {
    name: "힙쓰러스트",
    english_name: "hip_thrust",
    display_name: "힙쓰러스트",
    muscle_group: "legs",
    secondary_muscles: %w[glutes hamstrings],
    movement_pattern: "hinge",
    fitness_factors: %w[strength],
    equipment: %w[barbell bench],
    difficulty: 2,
    min_level: 2,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full],
    description: "둔근 발달의 최고 운동",
    form_tips: "정점에서 둔근 강하게 쥐어짜기",
    common_mistakes: "허리가 과신전, 무릎이 벌어짐"
  },

  # ============================================================
  # SHOULDERS (어깨)
  # ============================================================
  {
    name: "오버헤드프레스",
    english_name: "overhead_press",
    display_name: "오버헤드프레스",
    muscle_group: "shoulders",
    secondary_muscles: %w[triceps core],
    movement_pattern: "push",
    fitness_factors: %w[strength power],
    equipment: %w[barbell],
    difficulty: 3,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full],
    description: "어깨 근력의 기본 운동",
    form_tips: "코어 힘주기, 바벨 얼굴 옆으로 직선 경로",
    common_mistakes: "허리 과신전, 팔꿈치가 너무 벌어짐"
  },
  {
    name: "덤벨 숄더프레스",
    english_name: "dumbbell_shoulder_press",
    display_name: "덤벨 숄더프레스",
    muscle_group: "shoulders",
    secondary_muscles: %w[triceps],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[dumbbell],
    difficulty: 2,
    min_level: 2,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "덤벨을 이용한 어깨 프레스",
    form_tips: "팔꿈치 약간 앞으로, 어깨 높이에서 시작",
    common_mistakes: "팔꿈치가 너무 뒤로, 허리 아치"
  },
  {
    name: "레터럴레이즈",
    english_name: "lateral_raise",
    display_name: "레터럴레이즈",
    muscle_group: "shoulders",
    secondary_muscles: %w[traps],
    movement_pattern: "raise",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[dumbbell],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "측면 삼각근 발달 운동",
    form_tips: "새끼손가락 쪽이 위로, 어깨 높이까지만",
    common_mistakes: "승모근 사용, 반동 사용, 너무 높이 올림"
  },
  {
    name: "페이스풀",
    english_name: "face_pull",
    display_name: "페이스풀",
    muscle_group: "shoulders",
    secondary_muscles: %w[rear_delts traps rhomboids],
    movement_pattern: "pull",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[cable],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full],
    description: "후면 삼각근과 회전근개 강화",
    form_tips: "팔꿈치 높게, 로프를 얼굴 양옆으로 당기기",
    common_mistakes: "팔꿈치가 내려감, 상체 스윙"
  },
  {
    name: "리어델트 플라이",
    english_name: "rear_delt_fly",
    display_name: "리어델트 플라이",
    muscle_group: "shoulders",
    secondary_muscles: %w[rear_delts rhomboids],
    movement_pattern: "pull",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[dumbbell],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "후면 삼각근 고립 운동",
    form_tips: "상체 숙이고 팔꿈치 약간 굽혀서 옆으로",
    common_mistakes: "등 근육으로 당김, 반동 사용"
  },

  # ============================================================
  # ARMS (팔)
  # ============================================================
  {
    name: "바벨컬",
    english_name: "barbell_curl",
    display_name: "바벨컬",
    muscle_group: "arms",
    secondary_muscles: %w[forearms],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[barbell],
    difficulty: 2,
    min_level: 2,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "이두근 기본 운동",
    form_tips: "팔꿈치 고정, 이두근으로만 수축",
    common_mistakes: "반동 사용, 팔꿈치가 움직임"
  },
  {
    name: "덤벨컬",
    english_name: "dumbbell_curl",
    display_name: "덤벨컬",
    muscle_group: "arms",
    secondary_muscles: %w[forearms],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[dumbbell],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "덤벨을 이용한 이두 운동",
    form_tips: "손목 회전(슈피네이션) 추가 가능",
    common_mistakes: "반동 사용, 너무 무거운 무게"
  },
  {
    name: "해머컬",
    english_name: "hammer_curl",
    display_name: "해머컬",
    muscle_group: "arms",
    secondary_muscles: %w[brachialis forearms],
    movement_pattern: "pull",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[dumbbell],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "상완근과 전완근 발달에 효과적",
    form_tips: "손바닥이 서로 마주보게, 팔꿈치 고정",
    common_mistakes: "반동 사용, 손목이 돌아감"
  },
  {
    name: "트라이셉 푸시다운",
    english_name: "tricep_pushdown",
    display_name: "트라이셉 푸시다운",
    muscle_group: "arms",
    secondary_muscles: [],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[cable],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "삼두근 기본 케이블 운동",
    form_tips: "팔꿈치 몸에 붙이고, 완전히 펴기",
    common_mistakes: "팔꿈치가 움직임, 상체 스윙"
  },
  {
    name: "트라이셉 익스텐션",
    english_name: "tricep_extension",
    display_name: "트라이셉 익스텐션",
    muscle_group: "arms",
    secondary_muscles: [],
    movement_pattern: "push",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[dumbbell cable],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: true,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "오버헤드 삼두 운동",
    form_tips: "팔꿈치를 귀 옆에 고정, 삼두로만 펴기",
    common_mistakes: "팔꿈치가 벌어짐, 어깨 사용"
  },

  # ============================================================
  # CORE (코어/복근)
  # ============================================================
  {
    name: "크런치",
    english_name: "crunch",
    display_name: "크런치",
    muscle_group: "core",
    secondary_muscles: [],
    movement_pattern: "flexion",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "기본 복근 운동",
    form_tips: "목이 아닌 복근으로 상체 들기, 시선 천장",
    common_mistakes: "목을 당김, 반동 사용"
  },
  {
    name: "플랭크",
    english_name: "plank",
    display_name: "플랭크",
    muscle_group: "core",
    secondary_muscles: %w[shoulders glutes],
    movement_pattern: "isometric",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: false,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "코어 안정성 운동",
    form_tips: "몸 전체 일직선, 엉덩이 너무 높거나 낮지 않게",
    common_mistakes: "허리가 처짐, 엉덩이가 들림"
  },
  {
    name: "레그레이즈",
    english_name: "leg_raise",
    display_name: "레그레이즈",
    muscle_group: "core",
    secondary_muscles: %w[hip_flexors],
    movement_pattern: "flexion",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[none],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "하복부 타겟 운동",
    form_tips: "허리가 뜨지 않게, 천천히 내리기",
    common_mistakes: "반동 사용, 허리 아치"
  },
  {
    name: "행잉레그레이즈",
    english_name: "hanging_leg_raise",
    display_name: "행잉레그레이즈",
    muscle_group: "core",
    secondary_muscles: %w[hip_flexors grip],
    movement_pattern: "flexion",
    fitness_factors: %w[strength muscular_endurance],
    equipment: %w[pull_up_bar],
    difficulty: 3,
    min_level: 3,
    bpm_compatible: true,
    tabata_compatible: false,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full medium],
    description: "매달려서 하는 고급 복근 운동",
    form_tips: "스윙 최소화, 골반 말아올리기",
    common_mistakes: "스윙 사용, 엉덩이 굴곡근만 사용"
  },
  {
    name: "싯업",
    english_name: "sit_up",
    display_name: "싯업",
    muscle_group: "core",
    secondary_muscles: %w[hip_flexors],
    movement_pattern: "flexion",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "전통적인 복근 운동",
    form_tips: "복근으로 상체 일으키기",
    common_mistakes: "목 당기기, 반동 사용"
  },
  {
    name: "바이시클 크런치",
    english_name: "bicycle_crunch",
    display_name: "바이시클 크런치",
    muscle_group: "core",
    secondary_muscles: %w[obliques],
    movement_pattern: "rotation",
    fitness_factors: %w[muscular_endurance],
    equipment: %w[none],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: true,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "복사근까지 타겟하는 운동",
    form_tips: "반대쪽 팔꿈치와 무릎이 만나도록",
    common_mistakes: "너무 빠르게 수행, 목 당기기"
  },

  # ============================================================
  # CARDIO (유산소)
  # ============================================================
  {
    name: "버피",
    english_name: "burpee",
    display_name: "버피",
    muscle_group: "cardio",
    secondary_muscles: %w[chest legs shoulders core],
    movement_pattern: "compound",
    fitness_factors: %w[cardiovascular power muscular_endurance],
    equipment: %w[none],
    difficulty: 3,
    min_level: 2,
    bpm_compatible: false,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "전신 유산소 + 근력 운동",
    form_tips: "푸시업 자세에서 점프까지 연결",
    common_mistakes: "푸시업 생략, 자세 불량"
  },
  {
    name: "점핑잭",
    english_name: "jumping_jack",
    display_name: "점핑잭",
    muscle_group: "cardio",
    secondary_muscles: %w[shoulders legs],
    movement_pattern: "compound",
    fitness_factors: %w[cardiovascular],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: false,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "기본 전신 유산소 운동",
    form_tips: "팔과 다리 동시에 벌렸다 모으기",
    common_mistakes: "동작이 너무 작음"
  },
  {
    name: "마운틴클라이머",
    english_name: "mountain_climber",
    display_name: "마운틴클라이머",
    muscle_group: "cardio",
    secondary_muscles: %w[core shoulders hip_flexors],
    movement_pattern: "compound",
    fitness_factors: %w[cardiovascular muscular_endurance],
    equipment: %w[none],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: false,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "플랭크 자세에서 달리기",
    form_tips: "엉덩이 높이 유지, 무릎을 가슴 쪽으로",
    common_mistakes: "엉덩이가 들림, 속도만 추구"
  },
  {
    name: "하이니",
    english_name: "high_knees",
    display_name: "하이니",
    muscle_group: "cardio",
    secondary_muscles: %w[hip_flexors core],
    movement_pattern: "compound",
    fitness_factors: %w[cardiovascular],
    equipment: %w[none],
    difficulty: 1,
    min_level: 1,
    bpm_compatible: false,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "제자리 높이 뛰기",
    form_tips: "무릎을 허리 높이까지, 팔 스윙",
    common_mistakes: "무릎이 충분히 올라오지 않음"
  },
  {
    name: "스쿼트점프",
    english_name: "squat_jump",
    display_name: "스쿼트점프",
    muscle_group: "cardio",
    secondary_muscles: %w[quadriceps glutes],
    movement_pattern: "squat",
    fitness_factors: %w[cardiovascular power],
    equipment: %w[none],
    difficulty: 2,
    min_level: 1,
    bpm_compatible: false,
    tabata_compatible: true,
    dropset_compatible: false,
    superset_compatible: true,
    rom_options: %w[full],
    description: "점프를 추가한 스쿼트",
    form_tips: "착지 시 무릎 굽혀서 충격 흡수",
    common_mistakes: "착지가 딱딱함, 무릎 충격"
  }
].freeze

# Create or update exercises
def seed_exercises
  EXERCISES_DATA.each do |exercise_data|
    exercise = Exercise.find_or_initialize_by(english_name: exercise_data[:english_name])
    exercise.assign_attributes(exercise_data)

    if exercise.save
      puts "✓ #{exercise.name} (#{exercise.english_name})"
    else
      puts "✗ #{exercise.name}: #{exercise.errors.full_messages.join(', ')}"
    end
  end

  puts "\n총 #{Exercise.count}개 운동 등록 완료"
end

seed_exercises if __FILE__ == $PROGRAM_NAME
