FROM ruby:3.4.1

WORKDIR /app

# Install dependencies
RUN apt-get update -qq && apt-get install -y postgresql-client

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application
COPY . .

# Run Sidekiq
CMD ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
